name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/virtual-environments#available-environments
        os: [ubuntu-latest, windows-latest, macos-latest, macos-10.15]
        qtltsver: ['5.15.2', '6.2.4'] # Qt LTS versions
        include:
          - os: macos-latest
            xcode: latest-stable
          # Target the same macOS setup as release workflow
          - os: macos-10.15 
            xcode: '10.3' # Supports macOS Mojave onwards

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: ${{ matrix.qtltsver }}
        modules: 'qtcharts'
        aqtversion: '==2.0.0'

    - name: MSVC Environment Setup
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Xcode Environment Setup
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    - name: Create Makefile
      run: qmake

    - name: Build (nmake)
      if: runner.os == 'Windows'
      run: nmake

    - name: Build (make)
      if: runner.os != 'Windows'
      run: make
