name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/virtual-environments#available-environments
        os: [ubuntu-latest, windows-latest, macos-latest, macos-11]
        qtltsver: ['5.15.2', '6.2.4'] # Qt LTS versions
        include:
          - os: macos-latest
            xcode: latest-stable
          # Target the same macOS setup as release workflow
          - os: macos-11 
            xcode: '11.7' # Supports macOS 10.15.2 (Catalina) onwards

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: ${{ matrix.qtltsver }}
        modules: 'qtcharts'
        aqtversion: '==2.0.0'

    - name: MSVC Environment Setup
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Xcode Environment Setup
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    - name: Configure Build
      shell: bash
      run: |
        if [[ -n "${Qt5_DIR}" ]]; then export CMAKE_PREFIX_PATH=${Qt5_DIR}; fi
        if [[ -n "${Qt6_DIR}" ]]; then export CMAKE_PREFIX_PATH=${Qt6_DIR}; fi
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release 

    - name: Build
      run: cmake --build build --config Release
