name: QMake

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        modules: 'qtcharts'

    - name: Create Makefile
      run: qmake

    - name: Build
      run: make

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        modules: 'qtcharts'

    - name: MSVC Environment Setup
      uses: ilammy/msvc-dev-cmd@v1

    - name: Create Makefile
      run: qmake

    - name: Build
      run: nmake

  build_macos:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        modules: 'qtcharts'
        setup-python: 'false'

    - name: Create Makefile
      run: qmake

    - name: Build
      run: make
